name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup ARM GCC Toolchain
              uses: carlosperate/arm-none-eabi-gcc-action@v1.11.1

            - name: Build project
              run: make
